### ISSUE TITLE
heat_map and Z score

### ISSUE THREAD

**Issue by saratrem** [HakaiInstitute/jsp-data#26]
Referencing to the graph " heat_map" (or figure 2 in the NAFAC 2018 report).

I thought Z score can only be used for a normal distribution curve. Did we confirm that each factor was normally distributed before using their Z score? I don't see that confirmation anywhere in the R coding files or report!  

Migration timing and sealice counts would not be expected to follow a normal distribution (huge peak for migration, long tail). From the Fork length graph (figure 6), rapidly it also doesn't seem normally distributed!

**Comment by Br-Johnson** [comment]
Non-parametric Z-scores should be investigated. A statistic that copes well with small sample sizes is also important. Currently, the Z scores are computed for the distribution of median migration dates for example which means we only have 4 or 5 values to run a test on. Normality tests have low power on small sample sizes which is why I originally justified using parametric Z scores.

**Comment by Br-Johnson** [comment]
I ran shapiro wilk tests for normality for each variable and then transformed for normality using an inverse normal transformation where needed (sockeye migration dates only).
